# Generated by Django 5.0.4 on 2024-04-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Награда')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'db_table': 'awards',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='media/%y/%m/%d/', verbose_name='Изображение')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('birthday', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата рождения')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
                'db_table': 'directors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('IMDB', 'IMDb'), ('KP', 'Кинопоиск')], max_length=150, null=True)),
                ('marks', models.FloatField(verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Номинация')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'db_table': 'nomination',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('poster', models.ImageField(upload_to='media/%y/%m/%d/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('data_of_release', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата выхода')),
                ('budget', models.CharField(blank=True, max_length=30, null=True, verbose_name='Бюджет')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('awards', models.ManyToManyField(blank=True, null=True, related_name='my_awards', to='cinema.awards')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director_of_film', to='cinema.director', verbose_name='Режиссёр')),
                ('genre', models.ManyToManyField(blank=True, null=True, related_name='my_genre', to='cinema.genre')),
                ('grade', models.ManyToManyField(blank=True, null=True, related_name='my_grade', to='cinema.grades')),
                ('nomination', models.ManyToManyField(blank=True, null=True, related_name='my_nomination', to='cinema.nomination')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'films',
            },
        ),
        migrations.AddField(
            model_name='director',
            name='best_films',
            field=models.ManyToManyField(blank=True, related_name='my_best_films', to='cinema.film', verbose_name='Лучшие фильмы'),
        ),
        migrations.AddField(
            model_name='director',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='my_films', to='cinema.film', verbose_name='Фильмы'),
        ),
    ]
