# Generated by Django 5.0.4 on 2024-05-05 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_awards_ceremony_alter_film_awards_alter_film_genre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='my_awards', to='cinema.awards', verbose_name='Награды'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='my_genre', to='cinema.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='film',
            name='grade',
            field=models.ManyToManyField(blank=True, related_name='my_grade', to='cinema.grades', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='nomination',
            field=models.ManyToManyField(blank=True, related_name='my_nomination', to='cinema.nomination', verbose_name='Номинации'),
        ),
    ]
