# Generated by Django 5.0.4 on 2024-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_actor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='cinema.actor', verbose_name='актеры'),
        ),
    ]
