# Generated by Django 5.0.4 on 2024-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_film_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/actors/'),
            preserve_default=False,
        ),
    ]
