# Generated by Django 5.0.4 on 2024-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_actor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.SlugField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
