# Generated by Django 5.0.4 on 2024-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_actor_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.CharField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
