# Generated by Django 5.0.4 on 2024-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_alter_actor_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors_films', to='cinema.film', verbose_name='Фильмы'),
        ),
    ]
