# Generated by Django 5.0.4 on 2024-07-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_actor_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, choices=[('film', 'Фильм'), ('serial', 'Сериал'), ('cartoon', 'Мультфильм'), ('anime', 'Аниме')], null=True, verbose_name='Категория'),
        ),
    ]
