# Generated by Django 5.0.4 on 2024-07-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_film_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='photo',
            field=models.ImageField(upload_to='static/media/%y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='static/media/%y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
