# Generated by Django 5.0.4 on 2024-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_director_photo_alter_film_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='film_actor', to='cinema.actor', verbose_name='актеры'),
        ),
    ]
