# Generated by Django 5.0.4 on 2024-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_alter_film_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='poster/%y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
