# Generated by Django 5.0.4 on 2024-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_country_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='country',
            name='films',
            field=models.ManyToManyField(blank=True, null=True, related_name='country_films', to='cinema.film', verbose_name='Фильмы'),
        ),
    ]
