# Generated by Django 5.0.4 on 2024-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_alter_country_options_country_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, choices=[('Италия', 'Италия'), ('France', 'Франция'), ('USA', 'США'), ('Denmark', 'Дания'), ('Russia', 'Россия'), ('Japan', 'Япония'), ('Belgium', 'Бельгия'), ('Germany', 'Германия'), ('Sweden', 'Швеция')], max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
