# Generated by Django 5.0.4 on 2024-07-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_alter_country_name_alter_country_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, choices=[('Италия', 'Италия'), ('Франция', 'Франция'), ('США', 'США'), ('Дания', 'Дания'), ('Россия', 'Россия'), ('Япония', 'Япония'), ('Бельгия', 'Бельгия'), ('Германия', 'Германия'), ('Швеция', 'Швеция')], max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
