# Generated by Django 5.0.4 on 2024-07-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0024_rename_movie_movieshots_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='user',
        ),
    ]
