# Generated by Django 5.0.4 on 2024-07-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0026_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
    ]
